- name: Add common packages
  apt:
    name: "{{ item.name }}"
    state: latest
  with_items:
    - {name: vim}
    - {name: screen}
    - {name: tmux}
    - {name: htop}
    - {name: curl}
  when: ansible_os_family == 'Debian'